name    'tracywebtech-dofirewall'
version '0.3.1'
source 'https://github.com/TracyWebTech/puppet-dofirewall'
author 'tracywebtech'
license 'GPL, Version 2.0'
summary 'Digital Ocean firewall configuration'
description 'Puppet module to configure firewall on Digital Ocean servers allowing traffic on private network from nodes connected to the same master'
project_page 'https://github.com/TracyWebTech/puppet-dofirewall'

dependency 'puppetlabs/firewall', '>= 1.0.0' 
